// Generated by https://quicktype.io

export interface Asistencia {
  idSolicitudServicio: number;
  idPersona:           number;
  idProveedor:         number;
  servicio:            string;
  cliente:             string;
  latitud:             number;
  longitud:            number;
  accuracy:            number;
  patente:             null;
  fechaSolicitud:      string;
  fechaSolicitudUtc:   string;
  fechaCreacion:       string;
  fechaCreacionUtc:    string;
  idEmeMbdb:           number;
  idSolMbdb:           number;
  emePerArchivo:       EmePerArchivo[];
  emePerPosicion:      EmePerPosicion[];
  persona:             null;
  proveedor:           null;
  idProveedorWeb:      number;
  idUsuarioWeb:        number;
  proveedorWeb:        null;
}

export interface EmePerArchivo {
  idEmePerArchivo:     number;
  idSolicitudServicio: number;
  nombreArchivo:       string;
  tipo:                Tipo;
  latitud:             number;
  longitud:            number;
  accuracy:            number;
  fechaCaptura:        string;
  fechaCreacion:       string;
  fechaCreacionLocal:  null;
  solicitudServicio:   null;
}

export enum Tipo {
  A = 'A',
  F = 'F',
}

export interface EmePerPosicion {
  idEmePerPosicion:    number;
  idSolicitudServicio: number;
  latitud:             number;
  longitud:            number;
  accuracy:            number;
  fechaCaptura:        string;
  fechaCreacion:       string;
  solicitudServicio:   null;
}
