// Generated by https://quicktype.io

export interface Cliente {
  idPersona:    number;
  nombres:      string;
  apellidos:    string;
  nroDocumento: string;
  telefono:     string;
  fechaCreacion: string;
}
