import { Proveedor } from './proveedor.model';

// Generated by https://quicktype.io

export interface Cliente {
  idPersona:    number;
  nombres:      string;
  apellidos:    string;
  nroDocumento: string;
  telefono:     string;
  fechaCreacion: string;
}

// Generated by https://quicktype.io

export interface Titular {
  idPersona:                  number;
  nombres:                    string;
  apellidos:                  string;
  nroDocumento:               string;
  telefono:                   string;
  email:                      string;
  ruc:                        null;
  direccion:                  null;
  urlImagen:                  null;
  pais:                       number;
  nroCuenta:                  null;
  personaJuridica:            boolean;
  usuarioCreacion:            number;
  fechaCreacion:              string;
  fechaCreacionUtc:           string;
  usuarioModificacion:        number;
  fechaModificacion:          string;
  fechaModificacionUtc:       null;
  idCliente:                  number;
  total:                      number;
  codigoVerificacion:         any[];
  configPersona:              any[];
  contactoPersonaContacto:    any[];
  contactoPersonaSolicitante: any[];
  delito:                     any[];
  dispositivo:                any[];
  historicoEvento:            any[];
  notificacion:               any[];
  personaCamara:              any[];
  personaGps:                 any[];
  personaPanel:               any[];
  personaProveedor:           any[];
  solicitudCliente:           any[];
  solicitudServicio:          any[];
  usoFuncionalidad:           any[];
  viajeSeguro:                any[];
  zona:                       any[];
  idProveedorWeb:             number;
  idUsuarioWeb:               number;
  proveedorWeb:               null;
}

// Generated by https://quicktype.io

export interface Dependiente {
  idPersona:                  number;
  nombres:                    string;
  apellidos:                  string;
  nroDocumento:               string;
  telefono:                   string;
  email:                      string;
  ruc:                        null;
  direccion:                  null;
  urlImagen:                  null;
  pais:                       number;
  nroCuenta:                  null;
  personaJuridica:            boolean;
  usuarioCreacion:            number;
  fechaCreacion:              string;
  fechaCreacionUtc:           string;
  usuarioModificacion:        number;
  fechaModificacion:          string;
  fechaModificacionUtc:       null;
  idCliente:                  number;
  total:                      number;
  codigoVerificacion:         any[];
  configPersona:              any[];
  contactoPersonaContacto:    any[];
  contactoPersonaSolicitante: any[];
  delito:                     any[];
  dispositivo:                any[];
  historicoEvento:            any[];
  notificacion:               any[];
  personaCamara:              any[];
  personaGps:                 any[];
  personaPanel:               any[];
  personaProveedor:           any[];
  solicitudCliente:           any[];
  solicitudServicio:          any[];
  usoFuncionalidad:           any[];
  viajeSeguro:                any[];
  zona:                       any[];
  idProveedorWeb:             number;
  idUsuarioWeb:               number;
  proveedorWeb:               null;
}

// Generated by https://quicktype.io

export interface Dispositivo {
  idDispositivo:         string;
  idPersona:             number;
  idProveedor:           number;
  imei:                  null;
  token:                 string;
  latitud:               number;
  longitud:              number;
  accuracy:              number;
  fechaPing:             string;
  fechaPingUtc:          string;
  os:                    string;
  osversion:             string;
  appversion:            string;
  restful:               boolean;
  fechaCreacion:         string;
  fechaCreacionUtc:      string;
  fechaModificacion:     string;
  fechaModificaciongUtc: null;
  fechaCreacionLocal:    null;
  eventoGeocerca:        any[];
  ubicacionDispositivo:  any[];
  persona:               null;
  proveedor:             Proveedor;
}

// Generated by https://quicktype.io

export interface CodigoVerificacion {
  idCodigoVerificacion: number;
  idPersona:            number;
  codigoCorreo:         string;
  estadoCorreo:         string;
  codigoSms:            string;
  estadoSms:            string;
  email:                string;
  fechaCreacion:        string;
  fechaModificacion:    string;
  persona:              null;
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

