// Generated by https://quicktype.io

export interface Gps {
  idGps:               number;
  idProveedor:         number;
  idPersona:           number;
  patente:             string;
  latitud:             number;
  longitud:            number;
  velocidad:           number;
  sentido:             number;
  fechaUltimaPosicion: string;
  usuarioCreacion:     number;
  usuarioModificacion: number;
  fechaCreacion:       string;
  fechaModificacion:   string;
  eventoGps:           any[];
  personaGps:          any[];
  ubicacionGps:        any[];
  proveedor:           null;
  idProveedorWeb:      number;
  idUsuarioWeb:        number;
  proveedorWeb:        null;
}
