import { Nivel } from './nivel.model';
import { Proveedor } from './proveedor.model';
import { Panel } from './paneles.model';
import { Gps } from './gps.model';
import { Camara } from './camara.model';

export interface PerfilNivel {
  idPerfilNivel:       number;
  idPerfil:            number;
  idNivel:             number;
  ver:                 string;
  crear:               string;
  editar:              string;
  eliminar:            string;
  usuarioCreacion:     number;
  usuarioModificacion: null;
  fechaCreacion:       string;
  fechaModificacion:   null;
  nivel:               Nivel;
}

export interface PerfilProveedor {
  idPerfilProveedor: number;
  idPerfil:          number;
  idProveedor:       number;
  proveedor:         Proveedor[];
}

// Generated by https://quicktype.io

export interface PersonaProveedor {
  idPersonaProveedor:        number;
  idTitular:                 number;
  idPersona:                 number;
  idProveedor:               number;
  estadoServicio:            string;
  recibirNotificacion:       null;
  nroCuenta:                 null;
  totalConnect:              boolean;
  fechaSincronizacion:       null;
  fechaSincronizacionUtc:    null;
  fechaCreacion:             string;
  fechaCreacionUtc:          string;
  usuarioCreacion:           number;
  usuarioModificacion:       number;
  fechaModificacion:         string;
  fechaModificacionUtc:      null;
  desocupado:                any[];
  eventoPersona:             any[];
  personaProveedorObservado: null;
  persona:                   null;
  proveedor:                 Proveedor;
  idProveedorWeb:            number;
  idUsuarioWeb:              number;
  proveedorWeb:              null;
}

// Generated by https://quicktype.io

export interface PersonaPanel {
  idPersonaPanel:       number;
  idPersona:            number;
  idPanel:              number;
  idZona:               number;
  alias:                string;
  alarma:               string;
  activado:             string;
  falloEneElec:         string;
  usuarioCreacion:      number;
  usuarioModificacion:  number;
  fechaCreacion:        string;
  fechaCreacionUtc:     string;
  fechaModificacion:    string;
  fechaModificacionUtc: string;
  panel:                Panel;
  persona:              null;
  zona:                 null;
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

// Generated by https://quicktype.io

export interface PersonaGps {
  idPersonaGps:         number;
  idGps:                number;
  idPersona:            number;
  alias:                string;
  notificarEvento:      string;
  usuarioCreacion:      number;
  usuarioModificacion:  null;
  fechaCreacion:        string;
  fechaCreacionUtc:     string;
  fechaModificacion:    null;
  fechaModificacionUtc: null;
  idGpsMbdb:            number;
  contador:             number;
  gps:                  Gps;
  persona:              null;
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}


// Generated by https://quicktype.io

export interface PersonaCamara {
  idPersonaCamara:       number;
  idCamara:              number;
  idZona:                number;
  idPersona:             number;
  nombre:                string;
  usuario:               string;
  password:              string;
  fechaCreacion:         string;
  fechaCreacionUtc:      string;
  permiteGrabacion:      boolean;
  fechaPermiteGrabacion: null;
  idClienteCamaraMbdb:   number;
  camaraCanal:           any[];
  camara:                Camara;
  persona:               null;
  zona:                  null;
}

