export interface ClienteList {
  nombres: string;
  apellidos: string;
  nroDocumento: string;
  telefono: string;
  email?: string;
  ruc: string;
  personaJuridica: string;
  esCliente?: any;
  esTitular: string;
  fechaCreacion: string;
  dependientes: number;
}

/*export interface ClienteList {
  idPersona: number;
  nombres: string;
  apellidos: string;
  nroDocumento: string;
  telefono: string;
  email?: string;
  ruc: string;
  personaJuridica: string;
  esCliente?: any;
  esTitular: string;
  tienePanel?: any;
  tieneGps?: any;
  tieneCamara?: any;
  fechaCreacion: string;
  fechaCreacionUtc: string;
  dependientes: number;
  total: number;
}*/

// Generated by https://quicktype.io

export interface ClientesEstadistica {
  totalAndroid:            number;
  porcentAndroid: number;
  totalIos:                number;
  porcentIos: number;
  total: number;
  versionesAndroid:        Versiones[];
  versionesIos:            Versiones[];
  personaDispositivoDroid: PersonaDispositivo[];
  personaDispositivoIos:   PersonaDispositivo[];
}

export interface PersonaDispositivo {
  nombres:      string;
  apellidos:    string;
  nroDocumento: string;
  telefono:     string;
  email?:        string;
  os:           string;
  appversion:   string;
  osversion:    string;
  fechaPing:    string;
}


export interface Versiones {
  version:    string;
  total:      number;
  porcentaje: number;
}


