
/* export class Usuario {
  public IdPerfilProveedor: number;
  public IdPerfil: number;
  public IdProveedor: number;
  public Nombres: string;
  public Apellidos: string;
  public NroDoc: string;
  constructor(
    public email: string,
  ) { }
} */

export class LoginData {
  constructor(
    public username: string,
    public password: string
  ) {}
}

// Generated by https://quicktype.io

export interface Usuario {
  idUsuario:            number;
  idPerfilProveedor:    number;
  idPerfil:             null;
  idProveedor:          null;
  nombres:              string;
  apellidos:            string;
  nroDoc:               null;
  username:             string;
  password:             string;
  confirmPassword:      null;
  direccion:            null;
  email:                string;
  telefono:             string;
  usuarioCreacion:      number;
  usuarioModificacion:  number;
  fechaCreacion:        string;
  fechaCreacionUtc:     null;
  fechaModificacion:    string;
  fechaModificacionUtc: null;
  estado:               Estado;
  resetPassword:        boolean;
  recordarme:           boolean;
  perfilProveedor:      PerfilProveedor;
  proveedor:            Proveedor;
  perfil:               Perfil;
  perfilNivel:          PerfilNivel[];
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

export enum Estado {
  A = 'A',
}

export interface Perfil {
  idPerfil:             number;
  descripcion:          string;
  usuarioCreacion:      number;
  usuarioModificacion:  number;
  fechaCreacion:        string;
  fechaCreacionUtc:     null;
  fechaModificacion:    string;
  fechaModificacionUtc: null;
  estado:               Estado;
  check:                boolean;
  ver:                  boolean;
  crear:                boolean;
  editar:               boolean;
  eliminar:             boolean;
  perfilNivel:          any[];
  proveedor:            any[];
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

export interface PerfilNivel {
  idPerfilNivel:       number;
  idPerfil:            number;
  idNivel:             number;
  ver:                 Crear;
  crear:               Crear;
  editar:              Crear;
  eliminar:            Crear;
  usuarioCreacion:     number;
  usuarioModificacion: null;
  fechaCreacion:       string;
  fechaModificacion:   null;
  nivel:               Nivel;
}

export enum Crear {
  N = 'N',
  S = 'S',
}

export interface Nivel {
  idNivel:              number;
  descripcion:          string;
  recurso:              string;
  url:                  string;
  estado:               Estado;
  icono:                string;
  usuarioCreacion:      number;
  usuarioModificacion:  number;
  fechaCreacion:        string;
  fechaCreacionUtc:     null;
  fechaModificacion:    string;
  fechaModificacionUtc: null;
  perfil:               any[];
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

export interface PerfilProveedor {
  idPerfilProveedor: number;
  idPerfil:          number;
  idProveedor:       number;
  proveedor:         any[];
}

export interface Proveedor {
  idProveedor:          number;
  idTipoProveedor:      number;
  nombre:               string;
  alias:                string;
  direccion:            string;
  telefono:             string;
  email:                string;
  check:                boolean;
  celular:              null;
  urlLogo:              string;
  urlBandera:           string;
  pais:                 null;
  dominioPais:          string;
  sistemaSeguridad:     string;
  fileBytes:            null;
  fileBytesBand:        null;
  urlWebService:        string;
  linkWeb:              string;
  estado:               Estado;
  usuarioCreacion:      number;
  fechaCreacion:        string;
  fechaCreacionUtc:     null;
  usuarioModificacion:  number;
  fechaModificacionUtc: null;
  fechaModificacion:    string;
  tipoProveedor:        null;
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}
