import { Perfil } from './perfil.model';
import { Proveedor } from './proveedor.model';
import { PerfilProveedor, PerfilNivel } from './relaciones.model';


export class LoginData {
  constructor(
    public username: string,
    public password: string
  ) {}
}

export interface UsuarioNewPwd {
  user: string;
  password: string;
  confirmPassword: string;
}

// Generated by https://quicktype.io

export interface Usuario {
  idUsuario:            number;
  idPerfilProveedor:    number;
  idPerfil:             null;
  idProveedor:          null;
  nombres:              string;
  apellidos:            string;
  nroDoc:               null;
  username:             string;
  password:             string;
  confirmPassword:      null;
  direccion:            null;
  email:                string;
  telefono:             string;
  usuarioCreacion:      number;
  usuarioModificacion:  number;
  fechaCreacion:        string;
  fechaCreacionUtc:     null;
  fechaModificacion:    string;
  fechaModificacionUtc: null;
  estado:               string;
  resetPassword:        boolean;
  recordarme:           boolean;
  perfilProveedor:      PerfilProveedor;
  proveedor:            Proveedor;
  perfil:               Perfil;
  perfilNivel:          PerfilNivel[];
  idProveedorWeb:       number;
  idUsuarioWeb:         number;
  proveedorWeb:         null;
}

