// Generated by https://quicktype.io

export interface ZonaPeligrosa {
  idGeocerca:            number;
  idProveedor:           number;
  nombre:                string;
  mensaje:               string;
  estado:                string;
  vertices:              null;
  visible:               boolean;
  nuevo:                 boolean;
  usuarioCreacion:       number;
  fechaCreacion:         string;
  fechaCreacionUtc:      string;
  usuarioModificacion:   null;
  fechaModificacion:     null;
  fechaModificacionUtc:  null;
  eventoGeocerca:        any[];
  vertice:               Vertice[];
  idProveedorNavigation: null;
  idProveedorWeb:        number;
  idUsuarioWeb:          number;
  proveedorWeb:          null;
}

export interface Vertice {
  idVertice:  number;
  idGeocerca: number;
  latitud:    number;
  longitud:   number;
  geocerca:   null;
}
